name = "OptiX"
uuid = "26fe1022-4504-4e51-8d8d-17afb7a72451"
authors = ["Roger Mateer <rogermateer@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
